name: tmt_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.1
  geolocator: ^12.0.0
  intl: ^0.19.0
  flutter_card_swiper: ^7.0.2
  flutter_swiper_null_safety: ^1.0.2
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.2
  book_my_seat: ^1.0.1
 
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  


  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets: 
    - assets/img/logo.png
    - assets/img/searchResult.png
    - assets/img/test.jpg
    - assets/img/iconGoogle.png
  uses-material-design: true
