name: tmt_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.1
  geolocator: ^12.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  


  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets: 
    - assets/img/logo.png
    - assets/img/searchResult.png
    - assets/img/test.jpg
  uses-material-design: true
